title: bryn::writing
markdown: kramdown
highlighter: rouge
repository: canmom/canmom.github.io
permalink: /:categories/:title
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
description: a record of existence // Bryn's writing and art archive
lang: en_GB
logo: /android-chrome-512x512.png
twitter:
  username: CanonicMomentum
social:
  name: Bryn Dickinson
  links:
    - https://twitter.com/CanonicMomentum
    - https://github.com/canmom
    - https://canmom.tumblr.com
    - https://canmom.itch.io
future: false
url: https://canmom.art