name: bryn::portfolio
markdown: rdiscount
repository: canmom/canmom.github.io
permalink: /:categories/:title
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - rdiscount
description: Programming portfolio and physics writing archive.
lang: en_GB
logo: /android-chrome-512x512.png
twitter:
  username: CanonicMomentum
social:
  name: Bryn Dickinson
  links:
    - https://twitter.com/CanonicMomentum
    - https://github.com/canmom
    - https://witches.town/@canmom
    - https://canmom.tumblr.com
rdiscount:
  extensions: [smart]